print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/dominicadams/Documents/GitHub/Final-Project/Final Project/Final Project/Assets/Models/ElevatorChairTableComputerSwordCup.mb"`)
{		
	file -o "/Users/dominicadams/Documents/GitHub/Final-Project/Final Project/Final Project/Assets/Models/ElevatorChairTableComputerSwordCup.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/dominicadams/Documents/GitHub/Final-Project/Final Project/Final Project/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/dominicadams/Documents/GitHub/Final-Project/Final Project/Final Project/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/dominicadams/Documents/GitHub/Final-Project/Final Project/Final Project/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
